### ISSUE TITLE
release 1.21 testing

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#1058]
Testing for:
#1057 
#1056 
#1055 
#1053 

- Prevent page bounce on clear file button click
- Remove the clear file button after initial file removal
- Clarify title text for review and score columns on Panel page.
- Add Panel and Permissions links to the grant dropdown menu
- Fix redirect on change of grant's short name
- Assign review on submission index page
- Redesign reviewer tab to remove drag/drop of review assignment

**Comment by lmkw** [comment]
Sorry, I put my comments in the above tickets instead of this central one. Let me re-copy so they're centralized
**#1057** Looks good
**#1056** i put in a short name that violated rules (had a character, !, that's not allowed) and when i clicked Update it gave me an error (expected behavior). then i went back and changed the short name to something that was acceptable but when i clicked Update another time, it gave me the same error and in the URL i could see it was using the incorrect short name (the one with the !). then i tried it again, editing the short name to the same acceptable one, and it finally "took".

error message i got when short name was: https://competitions-staging.fsm.northwestern.edu/grants/againagain!
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

[Visit the homepage to see a list of current grants.](https://competitions-staging.fsm.northwestern.edu/)
**#1055** looks good
**#1053** 
    Assigned Bizzie Smalls as a reviewer
    Went to the Submissions page
    Clicked Assign
    Selected Bizzie Smalls
    Clicked Assign to Review
    Nothing happens

I repeated this with user John Duck, same thing, nothing appears to happen when I click Assign to Review

**Comment by jseraf** [comment]
@lmkw updated to fix issues mentioned above

**Comment by jseraf** [comment]
as discussed via Teams

**Comment by lmkw** [comment]
Just a note that error with assigning to reviewer and nothing happening was due to expired review window. 
Error with short name was a bug in the gem.
All looks good now, with a few added enhancements (removing Assign button when review window exceeded and removing invalid characters immediately from short names)
