### ISSUE TITLE
Editable submissions

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#248]
- Save for later
- Editable file uploads

5 votes

**Comment by lmkw** [comment]
@fanglinnw , can you weigh in on this? We're looking for possible short-term solutions so users can save and come back to their submissions.

**Comment by fanglinnw** [comment]
@mattbaumann1 @jseraf Gary has a work-around in the Membership app for the known issue in ActiveStorage of losing file uploads during edit. Here's the relevant code:
https://github.com/NUARIG/membership/blob/a7140dc5c66a39243994f6038da354eb6bbcdae4/app/controllers/program_membership_applications_controller.rb#L131-L141

Membership allows applicant to save file uploads in an application that's not submitted. So I think this is possible in Competition too.

**Comment by fanglinnw** [comment]
Note: please don't use the above code I linked in Membership because it has a serious bug that's causing . me great pain right now.

**Comment by fanglinnw** [comment]
here's what I figured out so far. To preserve the previously uploaded file, you need to add a hidden field before the file_field, and turn on the direct_upload option on the field_field:
```
<%= form.hidden_field :file, value: form.object.file.signed_id if form.object.file.attached? %>
<%= form.file_field :file,  id: "#{document}_upload", direct_upload: true %>
```
It's important to place the hidden_field before the file_field to allow updating existing upload (the last param with the same key takes precedence and this behavior is ensured because that's how the check_box field works in Rails, see the "Gotcha" secion in https://apidock.com/rails/ActionView/Helpers/FormHelper/check_box).

With this, you don't need to do any hack in the controller for the "create" action.

However, for the "update" action, if the file is on a nested child record, in the Membership app I still need to explicitly call `attach` on each file to allow updates (see the `manually_attach_files` function here: https://github.com/NUARIG/membership/blob/703f330ea2e9e1ac316b11dc114f2cb2469b4564/app/controllers/program_membership_applications_controller.rb#L52). I'm still trying to figure out why.

**Comment by lmkw** [comment]
This does not include showing Saved but not Submitted Submissions in the admin's view of their grant. I'll open a second ticket for that

**Comment by mattbaumann1** [comment]
In some initial testing the changed_for_autosave? method does not seem like it is necessary in Rails 5 but @fanglinnw says that it will be required in Rails 6.

**Comment by firaswehbe** [comment]
Per discussion on 2/3/2020 -- saving a draft would require all the validations on the form that would be required on submission. We can revisit relaxing that later.
