### ISSUE TITLE
Send reminders to reviewers to complete their reviews

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#257]
2 votes

**Comment by lmkw** [comment]
This page is already pretty loaded with functions

<img width="971" alt="Screen Shot 2020-05-21 at 5 25 29 PM" src="https://user-images.githubusercontent.com/12861678/82612305-29f4fb80-9b88-11ea-8daa-504fed2740a2.png">

and the Reviewers tab doesn't lend itself to nudging reviewers, because it doesn't tell you if reviews are complete or incomplete.

Consequently, I would recommend adding a button on this screen to nudge reviewers

<img width="1013" alt="Screen Shot 2020-05-21 at 5 25 41 PM" src="https://user-images.githubusercontent.com/12861678/82612428-72141e00-9b88-11ea-97ad-049936420f6f.png">
I would insert a column directly to the right of the Review column. I'm not sure what can be done in terms of UI--a button that says Nudge Reviewer? Remind Reviewer? You could have a hover-over that says "Sends an email to reviewer reminding them to review". The email itself could say:

Hello [Reviewer First Name]
This is a friendly reminder that you've been assigned to review 

[Submission name]
[Submission name]

by [Review Close Date]

Please finish reviewing these submissions [link to Competitions]

Thank you,
[Admin name]

**Comment by jseraf** [comment]
@lmkw, @mattbaumann1 i think there should be a flash warning or something that shows up x # of days before reviews are due saying something like "This grant has incomplete reviews. [link]Send a reminder to complete their reviews by #date[/link]"
