### ISSUE TITLE
Exports csv, pdf, etc.

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#268]
3 votes

**Comment by firaswehbe** [comment]
This is a task definition ticket. CSV reports. PDF reports. Scores.

**Comment by jseraf** [comment]
Talked to the Cancer Center devs who recommended the [caxlsx gem](https://github.com/caxlsx/caxlsx) and Excel exports rather than CSV exports.

**Comment by lmkw** [comment]
Everything from a submission and reviews in a spreadsheet
Request from Kelly Carroll (Lurie Children), right now she cuts and pastes from NITRO into spreadsheets to circulate (where?)

**Comment by lmkw** [comment]
From Emily:
Would want to export all submissions and all reviews to Excel

From Lauren:
Having export options for submissions and reviews would be great. 
For the submissions, the attached excel is the data I collect from the RedCap. What is not attached this is also collected in the Redcap form is a .pdf abstract. Having this in CD2H would also mean that I would need to be able to upload some instructions documents (like to help them identify their specialty code and to give them the NIH definition of URM and disadvantaged background).
 
For the **reviews export** It would be good to export two different things: 
1. **An excel file with the applicant, proposal title, each reviewer, each reviewer’s name, each reviewer’s overall impact score and then the candidate’s average overall impact score.**     
2. **A docx export with the review comments for each applicant.** Even though it will take more time to save, I think separate exports for each applicants would be better than an export all. Exporting all at one time would not work as well because review comments vary in length and would force me to do the extra work anyway making sure reviews are all separate and that each applicant has a review starting on a “front page”. An important note about the reviews is that the export should have the reviewer name associated and either a) There is another export option for de-identified reviews or b) the export file should allow me to edit so I can remove the reviewer name.

**Comment by jseraf** [comment]
Item 2 mostly covered by the new reviews summary page per review. That page would need a "de-itentify reviewers" option added.

**Comment by jseraf** [comment]
implemented in other tickets
