### ISSUE TITLE
Revisit DeviseSAMLAuthenticatable customizations

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#360]
Revisit these issues: 
https://github.com/apokalipto/devise_saml_authenticatable/issues/created_by/mattbaumann1

i.e. Do we still need DeviseSamlAuthenticatable::CompetitionsIdpEntityIdReader

**Comment by jseraf** [comment]
1/2 day allotted for research. Open additional tickets or re-assess here.

**Comment by jseraf** [comment]
If we keep the code as-is, there's no spec coverage for it.

**Comment by mattbaumann1** [comment]
Changes made to the gem by the administrators since we last updated include fixing failing specs and integration for Rails 6 and appropriate specs. 

They have not incorporated any fixes for session_index.

If we wanted to create a pull request, it would take moving our overwritten code and merging it with the original files and then waiting for the admins to approve it.

Our code can be found in the following files. 
app/controllers/saml_sessions_controller.rb
app/models/user.rb
lib/devise_saml_authenticatable/competitions_idp_entity_id_reader.rb

More details can be found below.
https://github.com/apokalipto/devise_saml_authenticatable/issues/117
