### ISSUE TITLE
Logic to ignore required fields while saving as draft

### ISSUE THREAD

**Issue by firaswehbe** [NUARIG/competitions#366]
When a submission is saved as a draft instead of being submitted, the required fields should be relaxed to not required

**Comment by fanglinnw** [comment]
@mattbaumann1 @jpatel Here's the logic for validation for required field:
https://github.com/NUARIG/competitions/blob/2df7f73e010cac669aaae6df8d75003513948630/app/models/grant_submission/response.rb#L58

For this ticket, the core change would be changing this line to `if: -> { question.is_mandatory? && submission.state == 'submitted' }

In draft mode, this validation would be skipped because of the call to set_state() in the controller update action:

https://github.com/NUARIG/competitions/blob/2df7f73e010cac669aaae6df8d75003513948630/app/controllers/grant_submissions/submissions_controller.rb#L63

I don't think there are other major model-level changes than this and I don't see any front-end validation on the form yet. I think this should be a relative simple change.
