### ISSUE TITLE
Redesign submission form

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#383]
Redesign the submission form to use Foundation grid. 

Refactor:
grant_submissions/submissions/_section_field.html.erb
grant_submissions/submissions/responses/response.html.erb
grant_submissions/submissions/responses/_long_text_response.html.erb

Related to #81 and #352

**Comment by lmkw** [comment]
The guidance on creating forms like this is it should be WYSIWYG--not a WYSIWYG editor, but that when the user is creating their grant, what they see is pretty much what it will look like to an applicant, with enough difference so they know they are creating a grant not applying to one. However, in this respect, the existing design is--for example, the textbox for question text is tiny, whereas the one for help text spans almost the width of the page. And yet people put the bulk of text in question text instead of help text. 

One thing that might help with this is if the help text, as you enter it into the field, *looks* like help text (however we will render it when you're applying to the grant)

Another thing that might help is more feedback/dynamic response to what question type you are creating. Let's take a look at Google Forms and see what we can learn from it (e.g. presenting options automatically when you select the question type)
