### ISSUE TITLE
Contact CECD about use of the new Competitions

### ISSUE THREAD

**Issue by mattbaumann1** [NUARIG/competitions#539]
- [x] Contact Lauren about her experiences using the new version. Is anything missing?

- [x] Contact Emily to discuss who her users are. Are the external users associated with other institutions?

**Comment by mattbaumann1** [comment]
Emily's response for her extern applicants.
"If external they will always be affiliated with another institution."

**Comment by mattbaumann1** [comment]
Contact email was sent to Lauren on 7/1/2020. We are waiting on a response.

**Comment by lmkw** [comment]
From Lauren:

When all was said and done with CD2H, I think the main challenge was just that it was brand new and I had to ask the reviewers to log in before I could assign them.

I can't remember if this was an option or not (and if it was, I didn't use it but wish I did), but having a hard end date for updating reviews and scores but still letting reviews access the system to view information would be good. I had some frustrating conversations in the review meeting where a couple of reviewers insisted the score I recorded for them was incorrect, which was impossible because I grabbed it directly from CD2H. Investigating it  later, I discovered they had changed their scores the day of the meeting. 

I particularly liked the feature that allowed me to edit an applicants materials by switching to a draft mode. It made it very easy for me to ensure I had finalized the changes.
