### ISSUE TITLE
Add option to show/hide reviews to reviewers during the panel

### ISSUE THREAD

**Issue by jseraf** [NUARIG/competitions#706]
Request from Phil (via Keith)

**Comment by lmkw** [comment]
"Keith (and Rich) – thanks for asking. I don’t want panelists second-guessing reviewer’s comments before the panel meets. For me, this would create a bad precedent. We encourage debate and second-guessing during the panel meeting, because it’s open and equitable debate (all can participate). What I want to avoid is a shadow review process that undermines the fairness and confidentiality of the process. Make sense? Phil"

Laura will talk to Keith & Phil

**Comment by jseraf** [comment]
closed in #752
