### ISSUE TITLE
sign-out issue on staging related to turbo that throws a CORS error (Access-Control-Allow-Origin).

### ISSUE THREAD

**Issue by lmkw** [NUARIG/competitions#964]
Fix whatever is causing the signout redirect on staging not to work

**Comment by mattbaumann1** [comment]
The train of thought here is that these are firing as turbo-streams instead of full html reloads and this means they don't have the necessary information in the headers, which then causes the CORS error. 

And because these were link_to instead of button_to, adding turbo = false did not work. It still processed as a turbo stream. Documentation of it can be found in this issue.
https://github.com/hotwired/turbo/issues/119

After fixing this, then we ran into some issues with the removed custom CompetitionsIdpEntityIdReader which needs to be added back.

**Comment by mattbaumann1** [comment]
The issue with the CORS error and needing turbo=false can be found discussed on these two blog posts.
https://accidentaltechnologist.com/ruby-on-rails/hotwire-fix-for-cors-error-when-using-omniauth/
https://dev.to/rbazinet/hotwire-fix-for-cors-error-when-using-omniauth-3k36
